---
version: '3'
volumes:
  db-data:
    external: false
services:
  dev:
    build:
      context: '.'
      dockerfile: './docker/Dockerfile'
    entrypoint: './docker/entrypoint.sh'
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      NODE_OPTIONS: --max_old_space_size=8192
      NODE_ENV: development
    volumes:
      - '.:/var/www:cached'
      - $SSH_AUTH_SOCK:/ssh-agent # Linux
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev
