---
version: '3'
volumes:
  db-data:
    external: false
services:
  dev:
    build:
      context: '.'
      dockerfile: './docker/Dockerfile'
    entrypoint: './docker/entrypoint.sh'
    ports:
      - 9090:9090
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      NODE_OPTIONS: --max_old_space_size=8192
      NODE_ENV: development
    volumes:
      - '.:/var/www:cached'
      - $SSH_AUTH_SOCK:/ssh-agent # Linux
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: suarecipe_development
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
